## Change these first
owner: remplerus
repo: uptimestatus
sites:
  - name: Homepage
    url: https://rempler.com
    expectedStatusCodes:
    - 200
    - 201
    - 403
  - name: Panel
    url: https://panel.rempler.com
  - name: Maven
    url: https://maven.rempler.com
status-website:
  cname: status.rempler.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Remplers Uptimes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
